import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Read{' '}
        <Link href="/posts/first-post">
          <a>this page</a>
        </Link>

        <Image src="/images/profile.jpg" height={144} width={144} alt="haixiangyan"/>
      </main>
    </div>
  )
}
